"""empty message

Revision ID: a7cb591fe3b6
Revises: ffdc0a98111c
Create Date: 2021-08-05 15:04:55.953589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cb591fe3b6'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('image', sa.String(length=300), nullable=False))
    op.create_unique_constraint(None, 'users', ['image'])
    op.create_unique_constraint(None, 'users', ['lastName'])
    op.create_unique_constraint(None, 'users', ['firstName'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'image')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
