"""empty message

Revision ID: 906865849f8b
Revises: bb6151d61191
Create Date: 2021-08-23 22:54:21.597044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906865849f8b'
down_revision = 'bb6151d61191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entryId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entryId'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
